### ISSUE TITLE
Suggestion:  get_ip and get_port

### ISSUE THREAD

**Issue by Petruchio** [imanel/websocket-eventmachine-server#2]
Greetings.

With some research, it's possible to get the IP and remote port for the connecting client.  It would be nice to have a method call for these, though.  Maybe store them in instance variables on connection (since they won't be changing), and offer attribute readers.  Or, of course, you could add them as parameters to onopen and onclose.

I presently have to call Socket.unpack_sockaddr_in( get_peername ) in onopen and then store the result, because I want to be able to report which connection is closing during onclose.  This is a bit awkward, and it would be nice if it wasn't necessary.

You might also either disable get_peername or give it stored information to use before onclose, because it presently doesn't work there.

Thanks for your consideration.

**Comment by imanel** [comment]
Shouldn't this be constant in all calls?

```ruby
WebSocket::EventMachine::Server.start(:host => "0.0.0.0", :port => 9001) do |ws|
    ws.onopen do
      puts ws.inspect
    end

  ws.onclose do
    puts ws.inspect
  end
end
```

I'm usually tracking it this way. If you need to have access to IP address and port that you can call `ws.get_peername` anywhere in code. Please confirm - I might be missing something.

**Comment by Petruchio** [comment]
```ruby
ws.onclose do
  ws.get_peername
end
#=> nil
```
Which is why I need to save it earlier.  Having dug into your code, though, I now see that this happens below, at the eventmachine level. I think that if get_peername should work there, it's probably not your problem to fix.

To give you a sense of what I had in mind, consider this:
```ruby
require 'websocket-eventmachine-base'
require 'ipaddr'

module WebSocket
  module EventMachine

    # WebSocket Server (using EventMachine)
    # @example
    #   WebSocket::EventMachine::Server.start(:host => "0.0.0.0", :port => 8080) do |ws|
    #     ws.onopen    { ws.send "Hello Client!"}
    #     ws.onmessage { |msg| ws.send "Pong: #{msg}" }
    #     ws.onclose   { puts "WebSocket closed" }
    #     ws.onerror   { |e| puts "Error: #{e}" }
    #   end
    class Server < Base

      attr_reader :get_ip, :get_port

      ###########
      ### API ###
      ###########

      # Start server
      # @param options [Hash] The request arguments
      # @option args [String] :host The host IP/DNS name
      # @option args [Integer] :port The port to connect too(default = 80)
      def self.start(options, &block)
        ::EventMachine::start_server(options[:host], options[:port], self, options) do |c|
          port, ip = *Socket.unpack_sockaddr_in( c.get_peername )
          c.instance_variable_set :@get_port, port
          c.instance_variable_set :@get_ip,   IPAddr.new(ip)
          block.call(c)
        end
      end

```
That gives me a get_ip and a get_host method, which means I don't have to unpack the peername myself, and it means I have them available during onclose, even if get_peername isn't useful there.

**Comment by imanel** [comment]
In `websocket-eventmachine-base` v1.2.0 you have access to full handshake in `onopen` call - it should have all informations needed.
